alias djm="poetry run $PWD/manage.py migrate"
alias djmm="poetry run $PWD/manage.py makemigrations"
alias djs="poetry run $PWD/manage.py shell"
alias djr="poetry run $PWD/manage.py runserver"
alias djsp="poetry run $PWD/manage.py shell_plus"
alias djrp="poetry run $PWD/manage.py runserver_plus"
